version: '4.0'
services:
  progress:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ".:/opt/progress"
      - "/opt/reactions/node_modules"
    environment:
       - NEXT_WEBPACK_USEPOLLING=true
       - CHOKIDAR_USEPOLLING=true
       - WATCHPACK_POLLING=true